name: E2E Tests (WordPress + Monthly Booking)

on:
  push:
    branches: [ devin/1754064671-monthly-booking-plugin ]
  pull_request:
    branches: [ devin/1754064671-monthly-booking-plugin ]

concurrency:
  group: e2e-${{ github.ref }}
  cancel-in-progress: true

jobs:
  e2e:
    runs-on: ubuntu-latest
    timeout-minutes: 10 # 診断のため時間を短縮

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install @wordpress/env
        run: npm i -g @wordpress/env
      
      - name: Start WordPress (for diagnosis)
        run: wp-env start || true

      # ▼▼▼▼▼ ここからが診断用のステップです ▼▼▼▼▼
      - name: Diagnose wp-env execution
        run: |
          echo "--- 1. Running 'wp --info' via wp-env ---"
          wp-env run cli wp --info

          echo "--- 2. Running 'wp plugin list' with 'set -x' to see exact command ---"
          set -x
          wp-env run cli wp plugin list
          set +x
          
          echo "--- 3. Checking PATH inside the container ---"
          wp-env run cli printenv PATH
      # ▲▲▲▲▲ ここまでが診断用のステップです ▲▲▲▲▲

      - name: Force failure to prevent further steps
        run: |
          echo "Diagnosis complete. This job will now fail intentionally."
          exit 1
