name: Devcontainer Validate

on:
  push:
    branches: [ main, fix/**, docs/** ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Lint devcontainer
        uses: devcontainers/ci@v0.3
        with:
          subFolder: .devcontainer
          action: 'lint'

  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node for CLI
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install Dev Container CLI (@latest)
        shell: bash
        run: |
          set -euxo pipefail
          npm -v
          # グローバルに入らない環境もあるため npx フォールバックを用意
          npm install -g @devcontainers/cli@latest || true
          if ! command -v devcontainer >/dev/null 2>&1; then
            echo "Global install not found, falling back to npx..."
            echo 'npx -y @devcontainers/cli@latest --version' | bash
          else
            devcontainer --version
          fi
          docker --version
      - name: Build devcontainer (no postCreate)
        shell: bash
        run: |
          set -euxo pipefail
          # npx とグローバルの両対応で実行
          if command -v devcontainer >/dev/null 2>&1; then
            devcontainer build \
              --workspace-folder . \
              --config .devcontainer/devcontainer.json \
              --log-level info
          else
            npx -y @devcontainers/cli@latest build \
              --workspace-folder . \
              --config .devcontainer/devcontainer.json \
              --log-level info
          fi
      - name: Smoke 'up' (skip postCreate)
        shell: bash
        run: |
          set -euxo pipefail
          # コンテナ起動の成否のみ確認（postCreate はスキップ）
          if command -v devcontainer >/dev/null 2>&1; then
            devcontainer up \
              --workspace-folder . \
              --config .devcontainer/devcontainer.json \
              --skip-post-create \
              --id-label CI=true \
              --log-level info
          else
            npx -y @devcontainers/cli@latest up \
              --workspace-folder . \
              --config .devcontainer/devcontainer.json \
              --skip-post-create \
              --id-label CI=true \
              --log-level info
          fi
