name: E2E

on:
  pull_request:
  workflow_dispatch:

concurrency:
  group: e2e-${{ github.workflow }}-${{ github.event.pull_request.number || github.ref_name }}
  cancel-in-progress: true

jobs:
  e2e:
    runs-on: ubuntu-latest
    timeout-minutes: 25
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci
        shell: bash

      - name: Install Playwright browsers
        run: npx playwright install --with-deps chromium
        shell: bash

      - name: Install dos2unix
        run: sudo apt-get update && sudo apt-get install -y dos2unix
        shell: bash

      - name: "Preflight: verify runner and docker availability"
        run: |
          set -euo pipefail
          docker --version
          echo "node=$(node -v) npm=$(npm -v)"
        shell: bash

      - name: Install @wordpress/env
        run: npm i -g @wordpress/env
        shell: bash

      - name: Start WordPress env
        run: npx wp-env start
        shell: bash

      - name: "Setup WordPress in wp-env and seed (RES_COUNT=6)"
        run: |
          set -euo pipefail
          npx wp-env run cli wp rewrite structure '/%postname%/' --hard
          npx wp-env run cli wp rewrite flush --hard
          if ! npx wp-env run cli wp user get admin >/dev/null 2>&1; then
            npx wp-env run cli wp user create admin admin@example.com --role=administrator --user_pass="password"
          fi
          npx wp-env run cli wp plugin activate monthly-booking || true
          # Ensure calendar page exists at /monthly-calendar/ with correct shortcode
          PAGE_ID=$(npx wp-env run cli wp post list --post_type=page --pagename=monthly-calendar --format=ids | tail -n1 || true)
          if [ -z "$PAGE_ID" ]; then
            echo "Creating monthly-calendar page with [monthly_booking_calendar] shortcode"
            npx wp-env run cli wp post create --post_type=page --post_status=publish --post_title="Monthly Calendar" --post_name="monthly-calendar" --post_content='[monthly_booking_calendar]'
          else
            echo "monthly-calendar page exists: ID=$PAGE_ID"
          fi
          npx wp-env run cli wp rewrite flush --hard
          RES_LINE=$(npx wp-env run cli wp eval-file wp-content/plugins/monthly-booking/tests/fixtures/seed.php | tail -n1 || true)
          echo "$RES_LINE"
          SITEURL=$(npx wp-env run cli wp option get siteurl)
          echo "BASE_URL=${SITEURL}" >> "$GITHUB_ENV"
        shell: bash

      - name: Run Playwright tests (smoke)
        env:
          BASE_URL: ${{ env.BASE_URL }}
        run: npx playwright test --reporter=list,html --workers=2 --grep "@smoke"
        shell: bash

      - name: Upload Playwright artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-artifacts
          path: |
            playwright-report/
            test-results/
          retention-days: 7
