name: e2e

on:
  pull_request:
    branches: [ main ]
    types: [opened, synchronize, reopened, labeled, unlabeled]
  workflow_dispatch:
    inputs:
      runCrud:
        description: 'Run CRUD job'
        required: false
        default: 'false'
      runNightly:
        description: 'Run nightly-full'
        required: false
        default: 'false'
  schedule:
    - cron: "22 18 * * *" # JST03:22頃にnightly-full

concurrency:
  group: e2e-${{ github.ref }}
  cancel-in-progress: true

jobs:
  smoke:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      # Playwright browsers cache
      - name: Cache Playwright browsers
        id: pwcache
        uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright
          key: pw-${{ runner.os }}-${{ hashFiles('**/package-lock.json', '**/pnpm-lock.yaml') }}

      # If cache miss, install Chromium only (fast)
      - name: Install Playwright browsers (if cache miss)
        if: steps.pwcache.outputs.cache-hit != 'true'
        run: npx playwright install --with-deps chromium

      # wp-now WordPress versions cache
      - name: Cache wp-now WordPress versions
        uses: actions/cache@v4
        with:
          path: ~/.wp-now/wordpress-versions
          key: wpnow-${{ runner.os }}-wp682
          restore-keys: |
            wpnow-${{ runner.os }}-

      - name: Install deps
        run: npm ci

      - name: MU sync
        run: npm run mu:sync

      - name: Start wp-now + health wait
        run: bash scripts/wp-start.sh

      - name: Smoke tests
        run: npm run test:smoke

  crud:
    needs: smoke
    runs-on: ubuntu-latest
    timeout-minutes: 20
    if: |
      github.event_name == 'schedule' ||
      (github.event_name == 'workflow_dispatch' && inputs.runCrud == 'true') ||
      (github.event_name == 'pull_request' && contains(join(github.event.pull_request.labels.*.name, ','), 'run-crud'))
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Cache Playwright browsers
        id: pwcache
        uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright
          key: pw-${{ runner.os }}-${{ hashFiles('**/package-lock.json', '**/pnpm-lock.yaml') }}

      - name: Install Playwright browsers (if cache miss)
        if: steps.pwcache.outputs.cache-hit != 'true'
        run: npx playwright install --with-deps chromium

      - name: Cache wp-now WordPress versions
        uses: actions/cache@v4
        with:
          path: ~/.wp-now/wordpress-versions
          key: wpnow-${{ runner.os }}-wp682
          restore-keys: |
            wpnow-${{ runner.os }}-

      - name: Install deps
        run: npm ci

      - name: MU sync
        run: npm run mu:sync

      - name: Start wp-now + health wait
        run: bash scripts/wp-start.sh

      # Run CRUD tests if script exists; otherwise skip gracefully
      - name: CRUD tests
        run: |
          if npm run | grep -q "test:crud"; then
            npm run test:crud
          else
            echo "No test:crud script found; skipping CRUD suite on this PR."
          fi

  nightly-full:
    needs: smoke
    runs-on: ubuntu-latest
    timeout-minutes: 30
    if: |
      github.event_name == 'schedule' ||
      (github.event_name == 'workflow_dispatch' && inputs.runNightly == 'true')
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Cache Playwright browsers
        id: pwcache
        uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright
          key: pw-${{ runner.os }}-${{ hashFiles('**/package-lock.json', '**/pnpm-lock.yaml') }}

      - name: Install Playwright browsers (if cache miss)
        if: steps.pwcache.outputs.cache-hit != 'true'
        run: npx playwright install --with-deps chromium

      - name: Cache wp-now WordPress versions
        uses: actions/cache@v4
        with:
          path: ~/.wp-now/wordpress-versions
          key: wpnow-${{ runner.os }}-wp682
          restore-keys: |
            wpnow-${{ runner.os }}-

      - name: Install deps
        run: npm ci

      - name: MU sync
        run: npm run mu:sync

      - name: Start wp-now + health wait
        run: bash scripts/wp-start.sh

      - name: Full CRUD suite (skip gracefully if missing)
        run: |
          if npm run | grep -q "test:crud"; then
            npm run test:crud
          else
            echo "No test:crud script found; skipping nightly CRUD suite."
          fi
