name: E2E

on:
  pull_request:

concurrency:
  group: e2e-${{ github.workflow }}-${{ github.event.pull_request.number || github.ref_name }}
  cancel-in-progress: true

jobs:
  e2e:
    runs-on: ubuntu-latest
    timeout-minutes: 25
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install Playwright browsers
        run: npx playwright install --with-deps chromium
        shell: bash

      - name: Install dos2unix
        run: sudo apt-get update && sudo apt-get install -y dos2unix
        shell: bash

      - name: Install dependencies
        run: npm ci
        shell: bash

      - name: Normalize and make wp-setup executable
        run: |
          dos2unix scripts/wp-setup.sh
          chmod +x scripts/wp-setup.sh
        shell: bash

      - name: Preflight: verify secrets and BASE_URL reachability
        env:
          BASE_URL: ${{ secrets.BASE_URL }}
          WP_ADMIN_USER: ${{ secrets.WP_ADMIN_USER }}
          WP_ADMIN_PASS: ${{ secrets.WP_ADMIN_PASS }}
        run: |
          set -euo pipefail
          [[ -n "${BASE_URL:-}" ]] || { echo "::error::Missing secret: BASE_URL"; exit 1; }
          [[ -n "${WP_ADMIN_USER:-}" ]] || { echo "::error::Missing secret: WP_ADMIN_USER"; exit 1; }
          [[ -n "${WP_ADMIN_PASS:-}" ]] || { echo "::error::Missing secret: WP_ADMIN_PASS"; exit 1; }
          echo "::notice::BASE_URL host: $(echo "${BASE_URL}" | sed -E 's#https?://([^/]+)/?.*#\1#')"
          for i in {1..12}; do
            if curl -fsSL -o /dev/null "${BASE_URL}/wp-admin/"; then
              echo "BASE_URL reachable"; break
            fi
            echo "Waiting for BASE_URL to be reachable... ($i/12)"; sleep 5
          done
          curl -fsS -o /dev/null "${BASE_URL}/wp-admin/" || { echo "::error::BASE_URL not reachable from runner"; exit 1; }
        shell: bash

      - name: WordPress setup
        env:
          BASE_URL: ${{ secrets.BASE_URL }}
          WP_ADMIN_USER: ${{ secrets.WP_ADMIN_USER }}
          WP_ADMIN_PASS: ${{ secrets.WP_ADMIN_PASS }}
        run: scripts/wp-setup.sh
        shell: bash

      - name: Run Playwright tests
        env:
          BASE_URL: ${{ secrets.BASE_URL }}
          WP_ADMIN_USER: ${{ secrets.WP_ADMIN_USER }}
          WP_ADMIN_PASS: ${{ secrets.WP_ADMIN_PASS }}
        run: npx playwright test --reporter=list,html --workers=2
        shell: bash

      - name: Upload Playwright artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-artifacts
          path: |
            playwright-report/
            test-results/
