- name: Finalize permalinks & calendar page (no pager, inside container)
  shell: bash
  run: |
    set -euo pipefail
    npx wp-env run cli -- wp rewrite structure '/%postname%/' --hard
    npx wp-env run cli -- wp rewrite flush --hard

    # ★コンテナ内で pager を無効化して ID を取得（exit 127 を根絶）
    PID=$(npx wp-env run cli -- bash -lc 'WP_CLI_DISABLE_AUTO_PAGER=1 PAGER=cat LESS=-R wp post list --post_type=page --pagename=monthly-calendar --format=ids || true')
    if [ -z "${PID}" ]; then
      echo "Creating monthly-calendar page..."
      npx wp-env run cli -- bash -lc 'WP_CLI_DISABLE_AUTO_PAGER=1 PAGER=cat LESS=-R wp post create \
        --post_type=page \
        --post_status=publish \
        --post_title="Monthly Calendar" \
        --post_name="monthly-calendar" \
        --post_content="[monthly_calendar]"'
    else
      echo "monthly-calendar exists: ID=${PID}"
    fi
