name: e2e

on:
  pull_request:
    branches: [ main ]
    types: [opened, synchronize, reopened]
  workflow_dispatch:

concurrency:
  group: e2e-${{ github.ref }}
  cancel-in-progress: true

jobs:
  e2e-chromium:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    container: mcr.microsoft.com/playwright:v1.47.2-jammy
    env:
      MB_BASE_URL: http://localhost:8080
      MB_ADMIN_USER: admin
      MB_ADMIN_PASS: password
      npm_config_legacy_peer_deps: "true"
      NPX_YES: "1"
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: tests/e2e/package-lock.json

      - name: Cache Playwright browsers
        uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright
          key: pw-${{ runner.os }}-${{ hashFiles('tests/e2e/package-lock.json') }}

      - name: Install E2E deps
        working-directory: tests/e2e
        run: |
          if [ -f package-lock.json ]; then
            npm ci --no-audit --no-fund --legacy-peer-deps
          else
            npm i --no-audit --no-fund --legacy-peer-deps
          fi

      - name: Start Docker WP stack
        working-directory: tests/e2e
        run: npm run pretest:e2e

      - name: Health check (WordPress up)
        working-directory: tests/e2e
        run: |
          echo "Waiting for $MB_BASE_URL ..."
          for i in {1..60}; do
            curl -fsS "$MB_BASE_URL" >/dev/null && echo "WP up" && break
            sleep 2
          done

      - name: Run Playwright tests (Firefox primary)
        working-directory: tests/e2e
        run: npx playwright test --project=firefox

      - name: Upload Playwright report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: tests/e2e/playwright-report
          retention-days: 7

      - name: Upload Playwright traces/screenshots/videos
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-artifacts
          path: |
            tests/e2e/test-results
          retention-days: 7

      - name: Teardown Docker WP stack
        if: always()
        working-directory: tests/e2e
        run: npm run posttest:e2e
