name: E2E Tests (wp-env)
on:
  pull_request:
  workflow_dispatch:
concurrency:
  group: e2e-${{ github.ref }}
  cancel-in-progress: true
jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
      - name: "Setup Node"
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: "Install deps"
        run: npm ci
      - name: "Install wp-env"
        run: npm i -g @wordpress/env @wordpress/scripts
      - name: "Make wp-setup executable"
        run: chmod +x .github/scripts/wp-setup.sh
      - name: "Start wp-env & seed"
        run: .github/scripts/wp-setup.sh
      - name: "Check RES_COUNT"
        run: |
          echo "Looking for RES_COUNT..."
          grep -n "RES_COUNT=" -n seed.log || (echo "RES_COUNT not found" && exit 1)
      - name: "Show BASE_URL"
        run: echo "BASE_URL=${{ env.BASE_URL }}"
      - name: "Run Playwright tests (@smoke)"
        run: |
          npx playwright install --with-deps chromium
          npx playwright test --reporter=html --workers=2 --grep "@smoke"
        env:
          BASE_URL: ${{ env.BASE_URL }}
      - name: "Upload Playwright report"
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report
          if-no-files-found: warn
          retention-days: 7
      - name: "Upload test-results (traces/videos)"
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: test-results
          if-no-files-found: warn
          retention-days: 7
      - name: "Upload seed.log (proof)"
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: seed-log
          path: seed.log
          if-no-files-found: warn
          retention-days: 7
      - name: "Cleanup wp-env"
        if: always()
        run: npx wp-env stop || true
