name: e2e
on:
  pull_request:
    branches: [ main ]

jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps
        run: npm ci

      - name: Install Playwright test runner
        run: npm i -D @playwright/test@^1.46.0

      - name: Install browsers
        run: npx playwright install --with-deps

      - name: MU sync
        run: npm run mu:sync

      - name: Start wp-now
        run: npm run start

      - name: Wait for wp-now to be ready
        run: |
          for i in {1..40}; do
            code=$(curl -s -o /dev/null -w "%{http_code}" http://127.0.0.1:8888/ || echo 000)
            echo "health=$code"
            if [ "$code" = "200" ] || [ "$code" = "301" ]; then exit 0; fi
            sleep 1
          done
          echo "Server did not become healthy" >&2
          exit 1

      - name: Run tests
        run: npm run test:smoke
