name: E2E Tests

on:
  push:
    branches: [ main, develop, devin/* ]
  pull_request:
    branches: [ main, develop ]

concurrency:
  group: monthly-booking-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'npm'
    
    - name: Install dependencies
      run: npm install --no-audit --no-fund
    
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    
    - name: Start WordPress with wp-env
      run: |
        npm install -g @wordpress/env
        wp-env start
        echo "CAL_URL=http://localhost:8888" >> $GITHUB_ENV
    
    - name: Health check WordPress
      run: |
        echo "CAL_URL=$CAL_URL"
        echo "Waiting for WordPress to be ready..."
        for i in {1..12}; do
          if curl -fsSL "$CAL_URL" > /dev/null 2>&1; then
            echo "WordPress is ready at $CAL_URL!"
            break
          fi
          echo "Attempt $i/12: WordPress not ready at $CAL_URL, waiting 5 seconds..."
          sleep 5
        done
        curl -fsSL "$CAL_URL" || (echo "WordPress failed to start at $CAL_URL" && exit 1)
      env:
        CAL_URL: http://localhost:8888
    
    - name: Setup WordPress for testing
      run: |
        echo "Setting up WordPress environment for testing..."
        
        # Install plugin files to wp-env
        npx wp-env run cli wp plugin activate monthly-booking || echo "Plugin activation failed, continuing..."
        
        # Create monthly-calendar page with shortcode if it doesn't exist
        PAGE_ID=$(npx wp-env run cli wp post list --post_type=page --name=monthly-calendar --field=ID --format=csv | tail -n +2)
        if [ -z "$PAGE_ID" ]; then
          echo "Creating /monthly-calendar/ page with shortcode..."
          npx wp-env run cli wp post create --post_type=page \
            --post_title='予約カレンダー' \
            --post_name='monthly-calendar' \
            --post_status=publish \
            --post_content='[monthly_booking_calendar]'
        else
          echo "Page /monthly-calendar/ already exists (ID: $PAGE_ID)"
        fi
        
        # Set permalink structure and flush
        npx wp-env run cli wp rewrite structure '/%postname%/'
        npx wp-env run cli wp rewrite flush --hard
        
        # Verify setup
        echo "Verifying /monthly-calendar/ accessibility..."
        curl -fsSL "$CAL_URL/monthly-calendar/" | head -n 50 || echo "Page not accessible yet"
      env:
        CAL_URL: http://localhost:8888
    
    - name: Run Playwright tests
      run: |
        echo "CAL_URL=$CAL_URL"
        npm run test:e2e
      env:
        CAL_URL: http://localhost:8888
    
    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report
        path: playwright-report/**
        retention-days: 7
    
    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results
        path: test-results/**
        retention-days: 7
