name: E2E Smoke

on:
  push:
    branches: [ chore/stabilize-campaign-crud-tests ]
  pull_request:
    branches: [ chore/stabilize-campaign-crud-tests ]

jobs:
  smoke:
    runs-on: ubuntu-latest
    env:
      BASE_URL: http://127.0.0.1:8888

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: |
          npm ci || npm i
          npx playwright install --with-deps chromium

      - name: Create temp root plugin (QA endpoints)
        run: |
          cat > wp-now-plugin.php <<'PHP'
          <?php
          /**
           * Plugin Name: MB QA Temp Plugin
           */
          add_action('rest_api_init', function () {
            register_rest_route('mb-qa/v1', '/ping', [
              'methods'  => 'GET',
              'permission_callback' => '__return_true',
              'callback' => function () {
                return ['ok' => true, 'ts' => time()];
              }
            ]);
          });
          function _mb_qa_echo() { wp_send_json(['ok'=>true,'action'=>'mb_qa_echo','ts'=>time()]); }
          add_action('wp_ajax_mb_qa_echo', '_mb_qa_echo');
          add_action('wp_ajax_nopriv_mb_qa_echo', '_mb_qa_echo');
          PHP

      - name: Start wp-now (plugin mode) on :8888
        run: |
          nohup npx wp-now start --wp 6.8.2 --port 8888 --path . > wp-now.log 2>&1 &
          echo $! > wp-now.pid
          sleep 2

      - name: Health check (up to 240s)
        shell: bash
        run: |
          set +e
          set +o pipefail
          ok=0
          for i in $(seq 1 120); do
            code=$(curl -sS -o /dev/null -w '%{http_code}' "$BASE_URL/" || echo 000)
            echo "health[$i]=$code"
            if [ "$code" = 200 ]; then ok=1; break; fi
            sleep 2
          done
          if [ "$ok" != 1 ]; then
            echo "wp-now didn't become healthy in time"
            echo "===== tail wp-now.log ====="; [ -f wp-now.log ] && tail -n 200 wp-now.log || true
            exit 1
          fi
          curl -sS "$BASE_URL/" | head -c 200 || true

      - name: Sanity POST admin-ajax (mb_qa_echo)
        shell: bash
        run: |
          code=$(curl -s -o resp.json -w '%{http_code}' -X POST -d "action=mb_qa_echo" "$BASE_URL/wp-admin/admin-ajax.php" || true)
          echo "status=$code"
          head -c 300 resp.json || true; echo
          if [ "$code" != "200" ]; then
            echo "===== wp-now.log (tail) =====" || true
            [ -f wp-now.log ] && tail -n 200 wp-now.log || true
            exit 1
          fi

      - name: Run smoke tests
        run: BASE_URL=$BASE_URL npm run test:smoke

      - name: Upload Playwright report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report
          if-no-files-found: ignore

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: test-results
          if-no-files-found: ignore

      - name: Upload wp-now log
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: wp-now.log
          path: wp-now.log
          if-no-files-found: ignore
