name: E2E Smoke

on:
  push:
    branches: [ chore/stabilize-campaign-crud-tests ]
  pull_request:
    branches: [ chore/stabilize-campaign-crud-tests ]
  workflow_dispatch: {}

jobs:
  smoke:
    runs-on: ubuntu-latest
    env:
      npm_config_legacy_peer_deps: "true"
      NPX_YES: "1"
