name: e2e / smoke

on:
  push:
    branches: [ chore/stabilize-campaign-crud-tests ]
  pull_request:
    branches: [ chore/stabilize-campaign-crud-tests ]

jobs:
  smoke:
    runs-on: ubuntu-latest
    env:
      BASE_URL: http://localhost:8888
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm

      - name: Install dependencies
        run: npm ci --no-audit --no-fund || npm install --no-audit --no-fund
      - name: Install Playwright browsers & system deps
        run: npx playwright install --with-deps chromium


      - name: Start WordPress (wp-now) in background
        run: |
          nohup npx wp-now start --wp 6.8.2 --port 8888 --path . > wp-now.log 2>&1 &
          echo "wp-now started"; sleep 1

      - name: Debug pre-check (ps/ss and wp-now.log head)
        shell: bash
        run: |
          echo "== ps -ef | grep -E \"wp-now|php\" =="
          ps -ef | grep -E "wp-now|php" || true
          echo "== ss -ltnp | grep 8888 =="
          ss -ltnp | grep 8888 || true
          echo "== wp-now.log (head 60) =="
          head -n 60 wp-now.log || true
      - name: Health check (wait up to ~60s)
        shell: bash
        run: |
          for i in {1..90}; do
            code1=$(curl -s -o /dev/null -w '%{http_code}' "$BASE_URL/" || true)
            code2=$(curl -s -o /dev/null -w '%{http_code}' "http://127.0.0.1:8888/" || true)
            echo "health(localhost)=$code1 health(127.0.0.1)=$code2"
            if [ "$code1" = "200" ] || [ "$code2" = "200" ]; then exit 0; fi
            sleep 2
          done
          echo "::error::wp-now did not become healthy in time"
          echo "===== wp-now.log (tail) ====="
          tail -n 200 wp-now.log || true
          exit 1
