name: e2e / smoke

on:
  push:
    branches: [ chore/stabilize-campaign-crud-tests ]
  pull_request:
    branches: [ chore/stabilize-campaign-crud-tests ]

jobs:
  smoke:
    runs-on: ubuntu-latest
    env:
      BASE_URL: http://127.0.0.1:8888
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright (Chromium + deps)
        uses: microsoft/playwright-github-action@v1
        with:
          version: 1.46.0

      - name: Start WordPress (wp-now) in background
        run: |
          nohup npx wp-now start --wp 6.8.2 --port 8888 --path . > wp-now.log 2>&1 &
          echo "wp-now started"; sleep 1

      - name: Health check (wait up to ~60s)
        run: |
          for i in {1..30}; do
            code=$(curl -s -o /dev/null -w "%{%{http_code}}" $BASE_URL/ || true)
            echo "health=$code"
            [ "$code" = "200" ] && exit 0
            sleep 2
          done
          echo "wp-now did not become health